#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Game.Droid.Resource", IsApplication=true)]

namespace Game.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F050005
			public const int colorAccent = 2131034117;
			
			// aapt resource value: 0x7F050003
			public const int colorPrimary = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int colorPrimaryDark = 2131034116;
			
			// aapt resource value: 0x7F050002
			public const int launcher_background = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010002
			public const int battleboard = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int brawler_class = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int cauldren = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int d12 = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int dice_20 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int door = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int dungeon_door = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int euphrates_lab = 2130771977;
			
			// aapt resource value: 0x7F010010
			public const int gameover = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int garage = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int grey_door = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int home_background = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int hunter_class = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int icon_add = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int icon_cancel = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int icon_delete = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int icon_edit = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int icon_new = 2130771993;
			
			// aapt resource value: 0x7F010020
			public const int icon_save = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int item = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int items = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int knight = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int mechanic_class = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int mechanist_class = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int neonStairs = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int raygun = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int ringleader_class = 2130772008;
			
			// aapt resource value: 0x7F010029
			public const int score = 2130772009;
			
			// aapt resource value: 0x7F010030
			public const int sewer_gator = 2130772016;
			
			// aapt resource value: 0x7F010031
			public const int soldier_class = 2130772017;
			
			// aapt resource value: 0x7F010032
			public const int splashscreen = 2130772018;
			
			// aapt resource value: 0x7F010033
			public const int troll = 2130772019;
			
			// aapt resource value: 0x7F010034
			public const int village = 2130772020;
			
			// aapt resource value: 0x7F010035
			public const int xamarin_logo = 2130772021;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020002
			public const int sliding_tabs = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int toolbar = 2130837507;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030002
			public const int Tabbar = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040002
			public const int icon = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int icon_round = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int launcher_foreground = 2130968580;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060004
			public const int AppCompatDialogStyle = 2131099652;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int MainTheme_Base = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
